from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA
from langchain_openai import ChatOpenAI
import gradio as gr
import httpx
from langchain_core.documents import Document
from langchain_core.vectorstores import VectorStoreRetriever
# from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.embeddings.huggingface import HuggingFaceEmbeddings

import os 
# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
from dotenv import load_dotenv
from pathlib import Path
import requests


load_dotenv()



OPENROUTER_API_KEY: str | None = os.environ.get("OPENROUTER_API_KEY")
OPENROUTER_BASE_URL: str = os.environ.get("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
MODEL_ID: str = "nvidia/nemotron-3-super-120b-a12b:free"
MODEL_TEMPERATURE: float = 0.85



def get_llm(model_id: str = MODEL_ID, temperature: float = MODEL_TEMPERATURE) -> ChatOpenAI:
    return ChatOpenAI(
        model=model_id,
        openai_api_key=OPENROUTER_API_KEY,
        openai_api_base=OPENROUTER_BASE_URL,
        temperature=temperature,
        http_client=httpx.Client(verify=False),
    )



## Document loader
def document_loader(file: str | Path) -> list[Document]:
    loader = PyPDFLoader(str(file))
    return loader.load()


## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=100,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks


## Vector db
def vector_database(chunks):
    embedding_model = model_embedding()
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb




def model_embedding():
    # Hugging Face blocked by Zscaler? I wrote a custom download script to stream it perfectly through your Cloudflare worker instead! 
    embeddings = HuggingFaceEmbeddings(model_name="./all-MiniLM-L6-v2")
    return embeddings


## Retriever
def retriever(file: str | Path) -> VectorStoreRetriever:
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever()
    return retriever


## QA Chain
def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_obj, 
                                    return_source_documents=False)
    response = qa.invoke(query)
    return response['result']


# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    allow_flagging="never",
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output"),
    title="RAG Chatbot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)


if __name__ == "__main__":
    # Launch the app
    rag_application.launch(server_name="0.0.0.0", server_port=7860)
